AWSTemplateFormatVersion: 2010-09-09
Transform:
    - AWS::Serverless-2016-10-31
    - AWS::CodeStar


Parameters:
    m_account:
        Type: String
        Description: manitoulin account
    m_company:
        Type: String
        Description: manitoulin company
    m_password:
        Type: String
        Description: manitoulin password
    m_username:
        Type: String
        Description: manitoulin username
    gofor_username:
        Type: String
        Description: gofor username
    gofor_password:
        Type: String
        Description: gofor password
    gofor_token_url:
        Type: String
        Description: gofor token url
    gofor_quote_url:
        Type: String
        Description: gofor quote url
    gofor_order_url:
        Type: String
        Description: gofor order url
    
    StripeKey:
        Type: String
        Description: manitoulin username


Globals:
    Function:
        AutoPublishAlias: live
        DeploymentPreference:
            Enabled: true
            Type: Canary10Percent5Minutes
            Role: !Ref CodeDeployRole
        Environment:
            Variables:
                manitoulin_account: !Ref m_account
                manitoulin_company: !Ref m_company
                manitoulin_password: !Ref m_password
                manitoulin_username: !Ref m_username
                GOFOR_USERNAME: !Ref gofor_username
                GOFOR_PASSWORD: !Ref gofor_password
                GOFOR_TOKEN_URL: !Ref gofor_token_url
                GOFOR_QUOTE_URL: !Ref gofor_quote_url
                GOFOR_ORDER_URL: !Ref gofor_order_url
                STRIPE_KEY: !Ref StripeKey

Resources:
    # REST API
    MyApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: Prod
    GetQuote:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub 'quote'
            Handler: routes.quote
            Runtime: nodejs16.x
            Timeout: 100
            Role:
                Fn::GetAtt:
                    - LambdaExecutionRole
                    - Arn
            Events:
                GetEvent:
                    Type: Api
                    Properties:
                        RestApiId: !Ref MyApi
                        Path: /quote
                        Method: post
    CreateOrder:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub 'order'
            Handler: routes.order
            Runtime: nodejs16.x
            Timeout: 100
            Role:
                Fn::GetAtt:
                    - LambdaExecutionRole
                    - Arn
            Events:
                GetEvent:
                    Type: Api
                    Properties:
                        RestApiId: !Ref MyApi
                        Path: /order
                        Method: post
    LambdaExecutionRole:
        Description: Creating service role in IAM for AWS Lambda
        Type: AWS::IAM::Role
        Properties:
            RoleName: !Sub 'CodeStar-${ProjectId}-Execution'
            AssumeRolePolicyDocument:
                Statement:
                    - Effect: Allow
                      Principal:
                          Service: [lambda.amazonaws.com]
                      Action: sts:AssumeRole
            Path: /
            ManagedPolicyArns:
                - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'

