const axios = require("axios");
const { getAuthToken, formatDate, pickVehicle } = require("./helper");
const { postalCodes } = require("./goforPostalCodes.json");

async function createGoforOrder({
    contactNumber,
    destinationAddress,
    destinationCity,
    destinationProvince,
    destinationZip,
    items,
    deliveryDate,
    deliveryTime,
  }) {
    try {
      const zip3letters = destinationZip.slice(0, 3);
      if (!postalCodes.includes(zip3letters)) {
        return {
          message: "Destination out of gofor service area",
          statusCode: 403,
        };
      }
      const { startDate, endDate, sameDay } = formatDate(deliveryDate, deliveryTime);
      const itemsDetails = items.map((item, index) => ({
        itemId: index,
        quantity: item.pieces,
        dimension: {
          unit: "CM",
          width: item.width,
          length: item.length,
          height: item.height,
        },
        weight: {
          unit: "KG",
          weight: item.weight,
        },
      }));
    
      const body = {
        deliveryType: "Scheduled",
        schedule: {
          startDate,
          endDate,
        },
        requestedVehicle: {
          vehicleId: pickVehicle(items)
        },
        customerType: "",
        pickUp: {
          pickUpType: "Curbside",
          pickUpContact: {
            firstName: "Alex",
            companyName: "DECKMART BUILDING SUPPLIES",
            mobile: {
              code: "",
              number: 9058125029,
            },
            email: {
              address: "",
            },
          },
          pickUpAddress: {
            addressLine1: "601 Garyray Dr",
            city: "NORTH YORK",
            postalCode: "M9L1P9",
            stateOrProvince: "ON",
            country: "CA",
          },
        },
        dropOffs: [
          {
            dropOffType: "Curbside",
            dropOffContact: {
              firstName: "Jaden", //TODO get the name
              mobile: {
                code: "",
                number: contactNumber,
              },
              email: {
                address: "",
              },
            },
            dropOffAddress: {
              addressLine1: destinationAddress,
              city: destinationCity,
              postalCode: destinationZip.toUpperCase(),
              stateOrProvince: destinationProvince.toUpperCase(),
              country: "CA",
            },
            orderNumber: "NM456", //TODO The order number generated by the client application's system for the delivery
            items: itemsDetails,
            specialInstructions: "",
            dropOffNotification: {
              notificationType: "None",
              IsCustomText: false,
            },
          },
        ],
      };

      const token = await getAuthToken();
      const goForQuoteUrl = process.env.GOFOR_ORDER_URL;
  
      const headers = {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
      };

      const result = await axios.post(goForQuoteUrl, body, { headers });
      console.log('Gofor Order result: ', result.data);
      const sameDayMessage = sameDay ? "order will be delivered same day" : "order will be delivered next day";
      return {
        message: "Successfully created gofor order, " + sameDayMessage,
        statusCode: 200,
      };
    } catch (err) {
      if (err.response?.data) {
        console.log('Gofor Order error: ', JSON.stringify(err.response?.data));
      }
      else {
        console.log('Gofor Order error: ', err.message);
      }
      return {
        message: err.response?.data?.response || err.message || "Unable to create gofor order",
        statusCode: err.response?.data?.code || 500,
      };
    }
  }

module.exports = { createGoforOrder };
